#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "rAxbQ/oryngD"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 52
#define COMBO_TERM_PER_COMBO

#define WHEEL_EXTENDED_SUPPORT
#define POINTING_DEVICE_HIRES_SCROLL_ENABLE
#undef POINTING_DEVICE_HIRES_SCROLL_EXPONENT
#define POINTING_DEVICE_HIRES_SCROLL_EXPONENT 1
#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
#define MOUSE_EXTENDED_REPORT
#define NAVIGATOR_TRACKBALL_CPI 25
#define NAVIGATOR_SCROLL_DIVIDER 50

#define AUTOMOUSE_LAYER 4
#define AUTOMOUSE_TIMEOUT 650
#define AUTOMOUSE_THRESHOLD 30
#define AUTOMOUSE_SCROLL_THRESHOLD AUTOMOUSE_THRESHOLD / NAVIGATOR_SCROLL_DIVIDER
#define RGB_MATRIX_STARTUP_SPD 60

#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
